version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: auth_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  spring-app:
    build:
      context: ./fit
      dockerfile: Dockerfile
    container_name: spring_api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8443:8443"
    restart: always

  frontend:
    build:
      context: ./fit-frontend
      dockerfile: Dockerfile
    container_name: fit_frontend
    depends_on:
      - spring-app
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:5173"
    restart: always

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
