services:
  db:
    image: postgres:latest
    container_name: auth_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: authpass
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
